import type { AgentId, CostClass } from '../types.js';

export type AgentDef = {
  id: AgentId;
  purpose: string;
  responsibilities: string[];
  inputs: string[];
  outputs: string[];
  allowedTools: string[];
  preferredWorker: string;
  fallbackWorker: string;
  validation: string[];
  failureBehavior: string;
  costPreference: CostClass;
  logging: string;
};

export const AGENTS: AgentDef[] = [
  {
    id: 'MASTER_ORCHESTRATOR',
    purpose: 'Only component that assigns work. Builds DAGs, routes cost, retries, resumes.',
    responsibilities: [
      'Receive jobs',
      'Build dependency graph',
      'Select cheapest capable worker',
      'Execute, validate, log, retry',
      'Require approval where configured',
      'Skip completed expensive work',
    ],
    inputs: ['job type', 'payload', 'release manifest'],
    outputs: ['updated job state', 'updated manifest', 'logs', 'cost ledger'],
    allowedTools: ['all workers via registry'],
    preferredWorker: 'deterministic',
    fallbackWorker: 'ollama',
    validation: ['every task writes status', 'idempotent skip of completed tasks'],
    failureBehavior: 'Fail the task, keep other completed tasks, retry with fallback chain',
    costPreference: 0,
    logging: 'job_id, release_id, agent, worker, task, timings, cost_class, retry_count',
  },
  {
    id: 'RECORD_ARCHITECT',
    purpose: 'Songwriting packages from SONGWRITING.md. Human approval before release pipeline.',
    responsibilities: ['Load SONGWRITING.md', 'Produce TITLE, LYRICS, STYLE, AVOID'],
    inputs: ['plain-language brief'],
    outputs: ['songwriting package JSON'],
    allowedTools: ['filesystem', 'ollama', 'premium-ai'],
    preferredWorker: 'ollama',
    fallbackWorker: 'premium-ai',
    validation: ['package contains title, lyrics, style, avoid'],
    failureBehavior: 'Queue for retry; never mark song approved',
    costPreference: 1,
    logging: 'brief hash, model, tokens estimate',
  },
  {
    id: 'RELEASE_DIRECTOR',
    purpose: 'Drive a release through stages after human song approval.',
    responsibilities: ['Advance current_stage', 'Keep DistroKid human-gated'],
    inputs: ['approved master path', 'manifest'],
    outputs: ['stage transitions'],
    allowedTools: ['ffmpeg', 'filesystem', 'metadata'],
    preferredWorker: 'deterministic',
    fallbackWorker: 'ffmpeg',
    validation: ['manifest schema'],
    failureBehavior: 'Hold stage, do not restart release',
    costPreference: 0,
    logging: 'stage, slug, checksum',
  },
  {
    id: 'VISUAL_DIRECTOR',
    purpose: 'Artwork and stills from title+lyrics. Overlay branding in code.',
    responsibilities: ['Cover 3000x3000', 'thumbs', 'social stills'],
    inputs: ['title', 'lyrics', 'existing art path'],
    outputs: ['artwork refs + checksums'],
    allowedTools: ['image-processing', 'ffmpeg'],
    preferredWorker: 'image-processing',
    fallbackWorker: 'ffmpeg',
    validation: ['dimensions, RGB, no secret leakage in prompts'],
    failureBehavior: 'Keep prior validated art; do not regenerate if complete',
    costPreference: 0,
    logging: 'source, dimensions, qc_status',
  },
  {
    id: 'VIDEO_FACTORY',
    purpose: 'MV, lyric, visualizer, canvas, shorts, reels via FFmpeg first.',
    responsibilities: ['Render only missing outputs', 'Cache intermediates'],
    inputs: ['master audio', 'stills', 'lyrics'],
    outputs: ['video file refs'],
    allowedTools: ['ffmpeg', 'ffprobe'],
    preferredWorker: 'ffmpeg',
    fallbackWorker: 'deterministic',
    validation: ['duration, resolution, silent canvas'],
    failureBehavior: 'Retry render of failed output only',
    costPreference: 0,
    logging: 'output kind, duration, bytes',
  },
  {
    id: 'PROMOTION_DIRECTOR',
    purpose: 'Platform-specific copy and campaign manifests. No identical spam.',
    responsibilities: ['titles, captions, hashtags, CTAs per platform'],
    inputs: ['release metadata', 'links'],
    outputs: ['promotion/*.json campaign'],
    allowedTools: ['deterministic', 'ollama'],
    preferredWorker: 'deterministic',
    fallbackWorker: 'ollama',
    validation: ['per-platform unique fields'],
    failureBehavior: 'Keep completed platforms',
    costPreference: 0,
    logging: 'platforms written',
  },
  {
    id: 'WEBMASTER',
    purpose: 'Release pages, catalog, SEO, sitemap, audits on apps/web (production site).',
    responsibilities: ['prepare catalog updates', 'run audits', 'never fake live deploy'],
    inputs: ['manifest', 'apps/web data files'],
    outputs: ['proposed site diffs', 'audit reports'],
    allowedTools: ['filesystem', 'playwright', 'lighthouse'],
    preferredWorker: 'deterministic',
    fallbackWorker: 'playwright',
    validation: ['lint/build/tests before deploy path'],
    failureBehavior: 'Queue review; no destructive site ops without approval',
    costPreference: 0,
    logging: 'files touched, audit scores',
  },
  {
    id: 'ANALYTICS_AGENT',
    purpose: 'Collect streams/views when APIs exist. Never invent numbers.',
    responsibilities: ['read configured analytics adapters only'],
    inputs: ['platform credentials if present'],
    outputs: ['analytics block on manifest'],
    allowedTools: ['filesystem'],
    preferredWorker: 'deterministic',
    fallbackWorker: 'deterministic',
    validation: ['no fabricated metrics'],
    failureBehavior: 'Leave analytics empty',
    costPreference: 0,
    logging: 'sources queried',
  },
  {
    id: 'BUSINESS_AGENT',
    purpose: 'Rights, DistroKid prep, money paths. Approval for financial/rights.',
    responsibilities: ['ISRC/UPC fields if known', 'never auto-upload DistroKid'],
    inputs: ['manifest', 'legal notes'],
    outputs: ['distribution prep folder refs'],
    allowedTools: ['filesystem'],
    preferredWorker: 'deterministic',
    fallbackWorker: 'deterministic',
    validation: ['no second ISRC for live titles'],
    failureBehavior: 'Block submit',
    costPreference: 0,
    logging: 'distributor, submission_status',
  },
  {
    id: 'QUALITY_CONTROL',
    purpose: 'Validate audio/art/copy/site before approval gate.',
    responsibilities: ['checksum, dimensions, required fields'],
    inputs: ['manifest'],
    outputs: ['qc_status fields'],
    allowedTools: ['ffprobe', 'filesystem'],
    preferredWorker: 'ffprobe',
    fallbackWorker: 'deterministic',
    validation: ['fail closed on missing master'],
    failureBehavior: 'Mark fail, do not publish',
    costPreference: 0,
    logging: ['checks run', 'failures'].join(', '),
  },
  {
    id: 'LOCAL_WORKER',
    purpose: 'Level 0/1 execution: FFmpeg, Python, hashes, Ollama.',
    responsibilities: ['run local tools', 'report availability'],
    inputs: ['worker command'],
    outputs: ['stdout summary without secrets'],
    allowedTools: ['ffmpeg', 'ollama', 'filesystem'],
    preferredWorker: 'deterministic',
    fallbackWorker: 'ollama',
    validation: ['exit code'],
    failureBehavior: 'Return to fallback router',
    costPreference: 0,
    logging: 'tool, duration',
  },
  {
    id: 'FALLBACK_AGENT',
    purpose: 'Walk preferred -> secondary -> local -> deterministic -> retry queue.',
    responsibilities: ['never restart whole release'],
    inputs: ['failed task + offers'],
    outputs: ['next offer or queued retry'],
    allowedTools: ['all'],
    preferredWorker: 'deterministic',
    fallbackWorker: 'ollama',
    validation: ['attempt log'],
    failureBehavior: 'Queue job for retry',
    costPreference: 0,
    logging: 'attempt chain',
  },
];

export function getAgent(id: AgentId): AgentDef {
  const found = AGENTS.find((a) => a.id === id);
  if (!found) throw new Error(`Unknown agent ${id}`);
  return found;
}
