name = "apex-citadel-api"
main = "src/index.ts"
compatibility_date = "2026-04-20"
account_id = "d6ec056b27a57bcf807a46b2e3379d60"

[vars]
APP_ENV = "production"
ACCESS_REQUIRED = "1"
OWNER_EMAIL = "mr.jwswain@gmail.com"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "apex_citadel"
database_id = "6ae6bd18-e43a-4c57-beba-0c3ed1b5a56b"

[triggers]
crons = ["*/5 * * * *"]
